# Generated by Django 5.1.4 on 2025-01-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='next_due_date',
        ),
    ]
